### ISSUE TITLE
Doesn't work on the Svelte REPL

### ISSUE THREAD

**Issue by samal-rasmussen** [bluwy/svelte-router#4]
Doesn't work on the Svelte REPL. No useful error message either. Just "[missing message]".

Minimal reproduction:
https://svelte.dev/repl/3634b1af7bfe43dd94de9ee5bd3fdae6?version=3.29.4

**Comment by bluwy** [comment]
The router navigates using the History API for both hash and path mode. so it doesn't work in the REPL (iframes). I wrapped the code in a try-catch and it points at the call to `history.replaceState`, which doesn't work as expected.

**Comment by samal-rasmussen** [comment]
I just posted this as a issue because I could get svelte-spa-router to work in the svelte repl. I guess that is because it uses window.location.hash instead of the history apt?

It is useful to be able to make little demos in the svelte repl, but if it requires you to do things that are against the design of svelte-router, then there's nothing to do about that. Feel free to close as wont fix.

**Comment by bluwy** [comment]
`svelte-spa-router` does change the `window.location.hash`, but only the hash of the iframe, which isn't reflected on the search bar. I don't have plans to include REPL support for now, will close this.
