### ISSUE TITLE
Problem when I write directly the Url into the browser

### ISSUE THREAD

**Issue by MatthieuQuantin** [bluwy/svelte-router#8]
Hi,

I use your Svelte-Router with your basic configuration (https://github.com/bluwy/svelte-router/tree/master/examples/basic)

It's possible to navigate with the nav links, but if I write directly the URL into the urlbar of the browser (ex : http://localhost:5000/user/foo), I have a 404 error.

**Comment by bluwy** [comment]
Hi, did you configure your server to serve the SPA correctly?

> Do note that path mode requires additional configuration on the server-side to serve a single HTML file for all URL paths. For example, the server should serve http://example.com/index.html when the user visits https://example.com/user/foo.

**Comment by MatthieuQuantin** [comment]
Thanks a lot for your response.

Do you have a link to explain how to configure that please ?

**Comment by bluwy** [comment]
It depends on the server you're using, so there isn't a definitive answer for it. If you're using `sirc-cli` make sure you [set the `-s` flag](https://github.com/bluwy/svelte-router/blob/cd16ef22c85179eb0e776801ff384236ccc288de/examples/basic/package.json#L8). If you're hosting on some other providers, you can check their docs on serving SPAs. The [vue router](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) docs have some information you can check out too.

**Comment by MatthieuQuantin** [comment]
With the flag -s it's perfect.

Thanks a lot.
Ans sorry for this wrong issue.
